package com.biancama.gui.swing.easyShipment.utils;

public enum EasyShipmentGuiConstants {
    CONFIG_PARAMETER, PARAM_INPUTTIMEOUT, PARAM_SHOW_SPLASH, PARAM_GENERAL_FONT_SIZE, DECORATION_ENABLED, PARAM_CUSTOM_BROWSER_USE, PARAM_CUSTOM_BROWSER, PARAM_CUSTOM_BROWSER_PARAM, PARAM_BROWSER, PARAM_SHOW_BALLOON, PARAM_THEME, PARAM_START_DOWNLOADS_AFTER_START, PARAM_INSERT_NEW_LINKS_AT

}
